general:
  input_method: webcam
  save_output: False
  track_length: 20

paths:
  model_path: 'models/'
  output_path: 'outputs/'
  video_path: 'videos/'

model: yolo26n.pt

detector: GeometryMethod

geometry_prams:
  threshold: 45  

gstreamer:
  source: 'nvarguscamerasrc'
  file: 'video/x-raw'
  memory: NVMM
  input_width: 1920
  input_height: 1080
  input_format: NV12
  framerate: 30
  flip_method: 2
  output_width: 960
  output_height: 720
  output_format: BGRx
  sink_format: BGR
  sink: appsink