general:
  input_method: gstreamer # acceptable inputs: webcam, video, gstreamer
  save_output: False
  track_length: 20 # How many points will be saved in the track
  show_output: True # Whether or not the video feed will be shown
  

paths:
  model_path: 'models/'
  output_path: 'outputs/'
  video_path: 'videos/'

model: yolo26n.engine # The Jetson uses .engine models
video: Mallard.mp4

detector: 
  type: GeometryMethod # Valid detectors: GeometryMethod
  threshold: 45 # Angle for GeometryMethod
  target_name: # Leave blank to check all objects
  confidence_threshold: 0.8 # The model returns a confidence score between 0 and 1
  refractory_frames: 40 # How many frames after a detection will the model ignore the track to prevent double events
  
gstreamer:
  source: 'nvarguscamerasrc'
  file: 'video/x-raw'
  memory: NVMM
  input_width: 1920
  input_height: 1080
  input_format: NV12
  framerate: 30
  flip_method: 2
  output_width: 960
  output_height: 720
  output_format: BGRx
  sink_format: BGR
  sink: appsink